---
- name: Bootstrap | Enable kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ kernel_modules }}"

- name: Bootstrap | Persist kernel modules
  template:
    src: modules.j2
    dest: "{{ module_load_path }}"
    mode: 'u=rw,g=r,o=r'

- name: Bootstrap | Configure kernel parameters
  sysctl:
    name: "{{ item }}"
    state: present
    sysctl_file: "{{ sysctl_file_path }}"
    value: 1
    reload: yes
  with_items: "{{ kernel_parameters }}"
