---
- name: Bootstrap | Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ bin_dir }}"
 
- name: Bootstrap | Add another bin dir to system-wide $PATH.
  copy:
    dest: /etc/profile.d/custom-path.sh
    content: 'PATH={{ bin_dir }}:$PATH'
