---
- name: Bootstrap | Ensure requirements required directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ etcd_release_dir }}"
    - "{{ bin_dir }}"

- include_tasks: etcdctl.yml

- include_tasks: jq.yml

- include_tasks: distro_packages.yml
  when: ansible_os_family not in ["CoreOS", "Container Linux by CoreOS", "Coreos", "Flatcar Container Linux by Kinvolk", "Flatcar"]
